# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++ -std=c++17
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers -Wno-parentheses-equality ${MODELICAUSERCFLAGS}   
CPPFLAGS="-I/home/clarafercas/Model_library/dynawo/dynawo/sources/Models/Modelica/Dynawo/Resources/Include" -I"/usr/bin/../include/omc/c" -I"/usr/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=MyNordic_initialized_TestCase_initialized -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=1 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas  -lm -lomcgc -lryu -lpthread -rdynamic -Wl,--no-undefined
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/usr/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/clarafercas/dynawo-notebooks/OpenModelica_only_users/Initialization/MyNordic_initialized"
MAINFILE=MyNordic_initialized.TestCase_initialized.c
MAINOBJ=MyNordic_initialized.TestCase_initialized.o
CFILES=MyNordic_initialized.TestCase_initialized_functions.c MyNordic_initialized.TestCase_initialized_records.c \
MyNordic_initialized.TestCase_initialized_01exo.c MyNordic_initialized.TestCase_initialized_02nls.c MyNordic_initialized.TestCase_initialized_03lsy.c MyNordic_initialized.TestCase_initialized_04set.c MyNordic_initialized.TestCase_initialized_05evt.c MyNordic_initialized.TestCase_initialized_06inz.c MyNordic_initialized.TestCase_initialized_07dly.c \
MyNordic_initialized.TestCase_initialized_08bnd.c MyNordic_initialized.TestCase_initialized_09alg.c MyNordic_initialized.TestCase_initialized_10asr.c MyNordic_initialized.TestCase_initialized_11mix.c MyNordic_initialized.TestCase_initialized_12jac.c MyNordic_initialized.TestCase_initialized_13opt.c MyNordic_initialized.TestCase_initialized_14lnz.c \
MyNordic_initialized.TestCase_initialized_15syn.c MyNordic_initialized.TestCase_initialized_16dae.c MyNordic_initialized.TestCase_initialized_17inl.c MyNordic_initialized.TestCase_initialized_18spd.c \
   MyNordic_initialized.TestCase_initialized_16dae_part0.c\
   MyNordic_initialized.TestCase_initialized_16dae_part1.c\
   MyNordic_initialized.TestCase_initialized_16dae_part2.c\
   MyNordic_initialized.TestCase_initialized_16dae_part3.c\
   MyNordic_initialized.TestCase_initialized_16dae_part4.c\
   MyNordic_initialized.TestCase_initialized_16dae_part5.c\
   MyNordic_initialized.TestCase_initialized_16dae_part6.c\
   MyNordic_initialized.TestCase_initialized_16dae_part7.c\
   MyNordic_initialized.TestCase_initialized_16dae_part8.c\
   MyNordic_initialized.TestCase_initialized_08bnd_part0.c\
   MyNordic_initialized.TestCase_initialized_08bnd_part1.c\
   MyNordic_initialized.TestCase_initialized_08bnd_part2.c\
   MyNordic_initialized.TestCase_initialized_08bnd_part3.c\
   MyNordic_initialized.TestCase_initialized_08bnd_part4.c\
   MyNordic_initialized.TestCase_initialized_06inz_part0.c\
   MyNordic_initialized.TestCase_initialized_06inz_part1.c\
   MyNordic_initialized.TestCase_initialized_06inz_part2.c\
   MyNordic_initialized.TestCase_initialized_06inz_part3.c\
   MyNordic_initialized.TestCase_initialized_06inz_part4.c\
   MyNordic_initialized.TestCase_initialized_06inz_part5.c\
   MyNordic_initialized.TestCase_initialized_06inz_part6.c\
   MyNordic_initialized.TestCase_initialized_06inz_part7.c\
   MyNordic_initialized.TestCase_initialized_06inz_part8.c\
   MyNordic_initialized.TestCase_initialized_06inz_part9.c\
   MyNordic_initialized.TestCase_initialized_06inz_part10.c

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) MyNordic_initialized.TestCase_initialized.makefile MyNordic_initialized.TestCase_initialized_literals.h MyNordic_initialized.TestCase_initialized_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that MyNordic_initialized.TestCase_initialized_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) MyNordic_initialized.TestCase_initialized_functions.h MyNordic_initialized.TestCase_initialized_literals.h $(OFILES)
	$(CC) -I. -o MyNordic_initialized.TestCase_initialized$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) MyNordic_initialized.TestCase_initialized_functions.h MyNordic_initialized.TestCase_initialized_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o MyNordic_initialized.TestCase_initialized$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f MyNordic_initialized.TestCase_initialized_records.o $(MAINOBJ)

bundle:
	@tar -cvf MyNordic_initialized.TestCase_initialized_Files.tar $(GENERATEDFILES)