/* Simulation code for MyNordic_initialized.TestCase_initialized generated by the OpenModelica Compiler OpenModelica 1.26.1~3-gfa676b4. */
#if !defined(MyNordic_initialized_TestCase_initialized__MODEL_H)
#define MyNordic_initialized_TestCase_initialized__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "MyNordic_initialized.TestCase_initialized_functions.h"

#define Complex_index 0
#define Complex__omcQ_27_2B_27_index 1
#define Complex__omcQ_27_2F_27_index 2
#define Complex__omcQ_27_2A_27_multiply_index 3
#define Complex__omcQ_27_2D_27_subtract_index 4
#define Complex__omcQ_27constructor_27_fromReal_index 5
#define Dynawo_Connectors_ComplexCurrentPuConnector_index 6
#define Dynawo_Connectors_ComplexVoltagePuConnector_index 7
#define Dynawo_NonElectrical_Logs_Timeline_logEvent1_index 8
#define Dynawo_Types_ComplexAdmittancePu_index 9
#define Dynawo_Types_ComplexApparentPowerPu_index 10
#define Dynawo_Types_ComplexCurrentPu_index 11
#define Dynawo_Types_ComplexImpedancePu_index 12
#define Dynawo_Types_ComplexVoltagePu_index 13
#define Dynawo_Types_ComplexAdmittancePu__omcQ_27_2A_27_multiply_index 14
#define Dynawo_Types_ComplexCurrentPu__omcQ_27_2D_27_subtract_index 15
#define Modelica_ComplexMath__omcQ_27abs_27_index 16
#define Modelica_ComplexMath_arg_index 17
#define Modelica_ComplexMath_conj_index 18
#define Modelica_ComplexMath_imag_index 19
#define Modelica_ComplexMath_real_index 20
#define Modelica_Math_atan3_index 21

extern void MyNordic_initialized_TestCase_initialized_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void MyNordic_initialized_TestCase_initialized_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void MyNordic_initialized_TestCase_initialized_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int MyNordic_initialized_TestCase_initialized_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_checkForAsserts(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int MyNordic_initialized_TestCase_initialized_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* MyNordic_initialized_TestCase_initialized_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* MyNordic_initialized_TestCase_initialized_relationDescription(int i);
extern void MyNordic_initialized_TestCase_initialized_function_initSample(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int MyNordic_initialized_TestCase_initialized_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* MyNordic_initialized_TestCase_initialized_linear_model_frame(void);
extern const char* MyNordic_initialized_TestCase_initialized_linear_model_datarecovery_frame(void);
extern int MyNordic_initialized_TestCase_initialized_mayer(DATA* data, modelica_real** res, short *);
extern int MyNordic_initialized_TestCase_initialized_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int MyNordic_initialized_TestCase_initialized_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int MyNordic_initialized_TestCase_initialized_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int MyNordic_initialized_TestCase_initialized_setInputData(DATA *data, const modelica_boolean file);
extern int MyNordic_initialized_TestCase_initialized_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void MyNordic_initialized_TestCase_initialized_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void MyNordic_initialized_TestCase_initialized_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int MyNordic_initialized_TestCase_initialized_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void MyNordic_initialized_TestCase_initialized_read_simulation_info(SIMULATION_INFO* simulationData);
extern void MyNordic_initialized_TestCase_initialized_read_input_fmu(MODEL_DATA* modelData);
extern void MyNordic_initialized_TestCase_initialized_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int MyNordic_initialized_TestCase_initialized_inputNames(DATA* data, char ** names);
extern int MyNordic_initialized_TestCase_initialized_dataReconciliationInputNames(DATA* data, char ** names);
extern int MyNordic_initialized_TestCase_initialized_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int MyNordic_initialized_TestCase_initialized_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int MyNordic_initialized_TestCase_initialized_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int MyNordic_initialized_TestCase_initialized_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "MyNordic_initialized.TestCase_initialized_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(MyNordic_initialized_TestCase_initialized__MODEL_H) */


